---
version: "3"
services:
 devopsdb:
   image: gowreeswarigeetha2000/mynewapp:dbimage
   ports:
     - "3306:3306"

 application:
   image: gowreeswarigeetha2000/mynewapp:appimage
   ports:
     - "2222:8080"
   depends_on:
     - "devopsdb"
